### ISSUE TITLE
Track scientific domain(s) of a workshop

### ISSUE THREAD

**Issue by anenadic** [carpentries/amy#1163]
This field should be a list selected from a multiple choice pre-defined set of values and would denote the scientific area(s) the students are coming from (should support multiple choices for workshops where students come from multiple domains).

The rationale behind this is that we (Software Sustainability Institute) often need to show numbers of people we trained or reached per domain (and would need to be able to link a domain with a funding body).

**Comment by chrismedrela** [comment]
> This field should be a list selected from a multiple choice pre-defined set of values

@anenadic What is the pre-defined set of values? Is it the same as `KnowledgeDomain` records, that is:
- Chemistry
- Civil, mechanical, chemical, or nuclear engineering
- Computer science/electrical engineering
- Don't know yet
- Economics/business
- Education
- Genetics, genomics, bioinformatics
- High performance computing
- Humanities
- Library and information science
- Mathematics/statistics
- Medicine
- Organismal biology (ecology, botany, zoology, microbiology)
- Physics
- Planetary sciences (geology, climatology, oceanography, etc.)
- Psychology/neuroscience
- Social sciences
- Space sciences

**Comment by anenadic** [comment]
That classification would be a great start. Can it have some minimal changes/additions and I assume it would have to go through a consultation process? I could come back with some proposed modifications in the case we have any. Thanks for responding quickly. 

It would also be good to have the same field for requests, and then move that over to events. So in the case the request does not go through to the event stage we still have a record of the domain. I could open a separate issue for this if need be.

**Comment by chrismedrela** [comment]
@anenadic both training and workshop requests do have a field for KnowledgeDomain (`TrainingRequest.domains` and `EventRequest.attendee_domains`). Do we need something similar for DC self-organized workshops requests?

> Can it have some minimal changes/additions and I assume it would have to go through a consultation process?

Sure, just keep in mind that the same set of options is reused on [training request form](https://amy.software-carpentry.org/forms/request_training/) ("areas of expertise") and [swc/dc workshops request form](https://amy.software-carpentry.org/forms/swc/request/) ("Domains or topic of interest for target audience").

**Comment by maneesha** [comment]
As I'm going through old issues here,  I'd like to open discussion on whether we need to open discussion on the domain fields listed here.  See also the issue raised here #1299.

**Comment by pbanaszkiewicz** [comment]
Possible ref: #1195

**Comment by ErinBecker** [comment]
@kariljordan did a lot of work about a year ago determining the appropriate domain categories to use across all of our surveys. We should use whatever categories were decided upon at that time for all of our systems. Keeping things consistent will allow us to compare data across our systems (and changing the categories will make it much more difficult to compare data across time).

**Comment by kariljordan** [comment]
Back when we ran the [survey language focus group](https://datacarpentry.org/blog/2017/10/survey-focus-group-update), @anenadic put together a [research domain classification spreadsheet](https://docs.google.com/spreadsheets/d/1QteXICrYMRXpG5IlmA0DY6BhFW7yuwc6-IZNcNJ5k2g/edit#gid=0) "that contains all different classifications for countries such as the US, Canada, Australia, South Africa, UK and any other that you think needs including and also compare it with the current classification from Carpentry surveys and AMY classification or requests/workshops." The domains in our surveys were compared with what's in AMY and the most frequent domains that came up in the "other" field in our survey. Check out the [comment in the pre-survey google document](https://docs.google.com/a/carpentries.org/document/d/1kmx-6y1OAz8KgpeR2to_kIbuyP4tJh369RCouaOkIrU/edit?disco=AAAACB6o9oM), and I'll ask @maneesha to weigh in as well when she's back from holiday. I'm happy to revisit the domains before the end of the year because we will be releasing learner assessment reports in Q4. After that release would be a great time to make any revisions that we need to our surveys.

**Comment by maneesha** [comment]
Currently we only ask this in the workshop inquiry form, not the request or self organized forms.  Leaving this issue open to consider why and how we may want to track this information.

**Comment by maneesha** [comment]
Closing as stale
