### ISSUE TITLE
Be nice to have link to upcoming training opportunities

### ISSUE THREAD

**Issue by symulation** [carpentries/amy#1214]
Hello!

When people fill out the form at https://amy.software-carpentry.org/forms/request_training/ it would likely be helpful share with them a link to the list of planned/possible upcoming training events.

**Comment by maneesha** [comment]
Hi @symulation - I'm cleaning out some old issues - this one's almost two years old :-)

We don't share a list of upcoming training events since they are intended for member sites and space permitting, to people applying through our open application process.  In both cases, people get explicit invitations to join.

Knowing this issue was raised a long time ago, do you still see a need to have something like this connected with the training application form?

**Comment by maneesha** [comment]
@symulation  I'm closing this for now.  Feel free to re-open if you see a need for this.  Thanks!
