### ISSUE TITLE
Associate AMY Persons with Memberships

### ISSUE THREAD

**Issue by jduckles** [carpentries/amy#1337]
In Amy person profiles we have "Affiliation" text field. This is ok for people listing what organization they feel they're a part of at any given time, but hard to use as a basis for linking together records. 

I'd like to be able to associate persons with memberships so we can do lookups/reports on the activities of persons (helpers, trainers, instructors) at the member organization. I see this as possibly an interface/UI for the membership lead (at the member org) to add/drop associations of instructors affiliated with their institution/organization. 

I also think it would be helpful for the instructors themselves to see associations they're a part of and have the ability to break their association with a member org if they move on to other work somewhere else. Complicating things even further, I think there will some people that have multiple of these associations, so it may be helpful for instructors to be able to credit their activities to one of their possibly many affiliations and also the option of crediting their effort to no specific affiliation.  

Lots to discuss here, but I can see this bit of metadata really improving our ability to show member orgs how their trained people are contributing. I can also see it as a boost to instructors as they build a log of effort over time, they can show how and where that effort went.

**Comment by pbanaszkiewicz** [comment]
> I see this as possibly an interface/UI for the membership lead (at the member org) to add/drop associations of instructors affiliated with their institution/organization.

In order to do that, membership lead would require access to personal data of all people in AMY.

> I also think it would be helpful for the instructors themselves to see associations they're a part of and have the ability to break their association with a member org if they move on to other work somewhere else.

Who would be able to associate an instructor with specific organization/membership? Only admins + membership lead? 

> Complicating things even further, I think there will some people that have multiple of these associations, so it may be helpful for instructors to be able to credit their activities to one of their possibly many affiliations and also the option of crediting their effort to no specific affiliation.

Currently I'm working on #1055 which puts effort of assigning trainees with memberships on admins.

What activities/efforts do you have in mind?

**Comment by maneesha** [comment]
I  believe the motivation behind this was so that for any of our member sites, we could know who they key contacts there were.  Right now, I would see only admins as able to do this.  An individual can list their own affiliation with a given site, but should not be able to make themselves the key contact for a member site.  

I think this needs more consideration, as for each member site we may have different key contacts (programmatic contact, finance contact, etc.).  These would need time frames associated with them.  We'd also have to consider what that key contact can see if they log in themselves.

@elizabethwilliams8 @Talishask  
**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by elizabethwilliams8** [comment]
@maneesha I agree that this needs more consideration, and I think that Option 3 is the most appropriate, since this association would be considered within the larger project of moving our Membership Database entirely to AMY (it is currently in Airtable)

**Comment by Talishask** [comment]
Agreed 3 -  It will also be important to consider graduations and moving institutions so that what is developed doesn't break if someone changes institutions.

**Comment by elizabethwilliams8** [comment]
Definitely 3, thank you!

**Comment by pbanaszkiewicz** [comment]
@maneesha please close if this has been fixed with #1775
