### ISSUE TITLE
add/revamp "Topic and lessons you're comfortable teaching"

### ISSUE THREAD

**Issue by raynamharris** [carpentries/amy#1409]
A number of LC, DC and Spanish lessons are missing from the "Topic and lessons you're comfortable teaching" section of the instructor profile. For instance:

* Missing [LC lessons](https://librarycarpentry.org/) including: Data intro for librarians, Data intro for archivist, Unix Shell, OpenRefine, Webscraping, Python, SQL
* Currently a number of [Data Carpentry Lessons](https://datacarpentry.org/lessons/) are listed  by topic (R, Python, spreadsheets) but it isn't clear how they related to specific workshops (ecology, genomics, social science). 
* There is no mention of the Spanish versions of Unix, Git, R, (all SWC) or Python (DC). In theory, someone's ability to teach these could be obtained by looking at what languages a instructor is fluent in, but fluency != comfortable teaching. 

 Here's a screen shot to view the current list of offerings. I'm not sure what is the best way to go about updating these, but I think a priority would be to add LC and then possible considering how the DC and spanish lessons are presented. 

![screen shot 2018-11-14 at 7 56 16 pm](https://user-images.githubusercontent.com/7544197/48525069-4d7b0f80-e848-11e8-8367-0a26732bcdd0.png)

**Comment by pbanaszkiewicz** [comment]
@raynamharris I'm open for suggestions on how this should look.

Maybe instead of "lessons" we should have "topics/technologies" (Python, R, OpenRefine, SQL, R-visualization, Shell, etc.), and additionally ask people for curricula they feel comfortable teaching (see screenshot below for list of curricula in AMY).
![screenshot from 2018-11-15 18-41-44](https://user-images.githubusercontent.com/72821/48571031-297e0380-e906-11e8-865e-a5ff27f1c2ec.png)

**Comment by raynamharris** [comment]
Thanks @pbanaszkiewicz! I like this a lot! My only concern is that instructors can no longer check that they are comfortable teaching, for instance, only shell but not git, r, or python. I like your suggested groupings, but it might be an issue for others. Perhaps @maneesha can weigh in on what would be most useful for helping find and place instructors in workshops. 

(Also, I didn't realize I mentioned this back in May. Thanks for finding and linking the related issues.)

**Comment by ErinBecker** [comment]
Thanks for adding the issue @raynamharris! It's a great idea to update that list. In our current workflow, we don't use this part of the Instructor profile for anything, but we have talked about in the future being able to use it for Instructor teaching assignments (to make it easier to identify candidates to teach a workshop). 

Since the Workshop Administration team would be the ones making use of this information in this use case, I want to make sure that their needs for this information are considered before making any changes. @maneesha @sheraaron - could you please weigh in on this revamp? What would be the most useful way to organize this information? Please also give a sense of urgency - how much of a priority is this? Should it be included in this release? Or is a later release ok? @libcce should also be asked about what should be listed in terms of LC curriculum.

**Comment by libcce** [comment]
Our core curriculum should be listed which you can find here:
https://librarycarpentry.org/lessons/
The core lessons are:
Intro to Data
Unix Shell
OpenRefine
Git

**Comment by maneesha** [comment]
Library Carpentry options are expanded in issue #1419.

As far as expanding this to allow instructors to choose lesson modules rather than entire curricula, I'll discuss this more with our workshop admin team and will follow up... likely not until January though!

**Comment by pbanaszkiewicz** [comment]
Hello everyone, thanks for your input. Issue #1419 mentioned by @Maneesha is going to be merged in this release. Please remember it only affects "Curricula" in AMY; this current issue, though, is about "Lesson" objects. They're only used to indicate what person feels comfortable teaching, and nowhere else.

**Comment by maneesha** [comment]
@pbanaszkiewicz Can we make the `workshops_lesson` table modifiable from the Django admin panel?

**Comment by pbanaszkiewicz** [comment]
@maneesha actually it is. If you go to AMY, click top-right menu, follow with "Django Admin" link, then look for "Lessons" under "WORKSHOPS" label you'll be able to add/edit/remove the lessons.

**Comment by pbanaszkiewicz** [comment]
@maneesha does that solve this issue?

**Comment by maneesha** [comment]
Yes, thanks @pbanaszkiewicz   
I'm going to keep this open for myself but there's nothing else we need from you.

**Comment by maneesha** [comment]
Closing this here as it's being discussed in #1513
