### ISSUE TITLE
Make plots that are publicly viewable

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1436]
We have plots like [workshops over time](https://amy.software-carpentry.org/reports/workshops_over_time/), [learners over time](https://amy.software-carpentry.org/reports/learners_over_time/), etc. that are accessible to logged in users.

Is it possible to have similar views that are publicly viewable?  (still keeping the underlying source data private)

If that's something we can do, I'll follow up more scoping out what I'm thinking about.

**Comment by fmichonneau** [comment]
I think it's a great idea. As we are thinking about which data we have and what we want to publicize, share with member organizations, and instructors, having this kind of data public would be very useful. We may want to consider not making this part of AMY though and use redash to make the data available so we could integrate these graphs on our websites for instance.

**Comment by maneesha** [comment]
Yes, I have been experimenting with what we can do on redash.  I wanted to see what was possible via AMY as well, to be aware of all options.

**Comment by pbanaszkiewicz** [comment]
@maneesha @fmichonneau due to AMY's release cycle (montly-ish) it's harder to incorporate changes here than it is in redash.

That said, I can work on publicly accessible statistics from our data, especially since I'm planning to touch access permissions (#1287) in the next major release anyway.

The statistics can be generated "in real time", or static (refreshed e.g. once a day) - the latter is a bit safer, since it happens outside of the server.

**Comment by maneesha** [comment]
Closing this in favor of exploring it in redash.
