### ISSUE TITLE
Allow admin user to edit membership variants

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1462]
The current member form allows these variants:
![image](https://user-images.githubusercontent.com/829690/52504380-4c8f1b00-2bb6-11e9-8445-904072833cde.png)

Can we have this list of variants be edited from the [admin console](https://amy.software-carpentry.org/admin/)?

**Comment by pbanaszkiewicz** [comment]
@maneesha: yes, it's possible, but it requires adding a relationship.

**Comment by maneesha** [comment]
Thanks @pbanaszkiewicz 
That would be useful for us so we can adjust membership categories depending on our programming.

**Comment by maneesha** [comment]
@Talishask Asking you for now, and maybe you want to take this back to Elizabeth.  

The current membership options for a site include Partner, Affiliate, Sponsor, etc., so they don't exactly match our membership models.   We can have @pbanaszkiewicz  change them if we want them to be some other categories.  We can also have him set things up so we can change these categories ourselves as needed (which would be more time consuming for him).  Do you see these changes as priorities? 


**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by Talishask** [comment]
4 - I would say 3 but I don't believe this is a project. Our current membership options are available for us to use so that moves this out of a priority update to a 'would be nice' update. We are currently developing a sponsorship model and have on the list for the near future to evaluate our membership models. So eventually we may need to update these options but I don't forsee that happening until sometime next year at the earliest. At that time it should be okay to just change the labels, we shouldn't need to have the ability to change them ourselves as needed.

**Comment by maneesha** [comment]
Revisiting this @pbanaszkiewicz 
We have had a few use cases in the past year where we would want to define membership levels ourselves.
