### ISSUE TITLE
Notification to admins when critical part of AMY is modified

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1523]
[possibly related to #795]

To ensure that no critical component of AMY gets edited without it being noticed, having a notification system with email alerts sent to admins when something in the Django Admin panel is edited would be useful. This is probably going to be critical for the email templates once they are in place, but even for tags or other elements that can be edited, alerting others that it's taken place would make things safer.

**Comment by pbanaszkiewicz** [comment]
Just leaving some notes here:

1. User actions in Django Admin are getting stored in [`LogEntry` model](https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#logentry-objects) provided by Django and are visible upon logging into Django Admin
![obraz](https://user-images.githubusercontent.com/72821/63713330-be237380-c83f-11e9-99d3-06b4956a3987.png)

2. We could perhaps reuse `LogEntry` to send notification when action occurs, but a more general way would be to react on [signals](https://docs.djangoproject.com/en/2.2/topics/signals/) sent out when crucial objects are being edited (e.g. Tags, Roles, Badges, EmailTemplates). Signals can be generated not only from the Django Admin actions, but also during normal using of AMY. Unfortunately they probably wouldn't prevent from the number of cases we had when a bug in Merging Events caused Tags to disappear.

**Comment by maneesha** [comment]
This is old, but is still something we need to consider.  
Because these changes need to be presented in context of project and program management work flows, I think automated notifications are only part of the solution.

Cuurently @pbanaszkiewicz  sends out a log with every release  of the changes that have been made.  I will be working on internal systems to ensure our [documentation](https://docs.carpentries.org/topic_folders/workshop_administration/amy_manual.html) stays up to date  (currently it is behind).  We also need systems to explicitly notify people of these changes and help them understand the context of the changes.

@pbanaszkiewicz  Can you provide some more information about what kinds of notifications could be automated or viewed from the admin panel?

**Comment by maneesha** [comment]
Closing this as this is all covered through existing project management and documentation procedures.
