### ISSUE TITLE
Workshop Request Form: Adding Host Tasks for SWC Submissions

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#1560]
When creating events from the WRF submissions the 'Host' task is being added automatically to the person who submitted the form for Mix/Match, LC & DC submissions but not for SWC submissions.

I've experienced this issue with Self-organized submissions, but I cannot speak to workshop requests or workshop inquiries. 

This is not an urgent fix - Since we are now using the host tag in the new survey workflow queries, this just means that I need to add the host manually but does not create a work stoppage.

**Comment by pbanaszkiewicz** [comment]
@Talishask host task creation when a Self-Organised Submission is being accepted doesn't depend on any tag. Actual logic is: "get Person from database, match personal name, family name and email" - this person receives the host task.

For me it looks like you had bad luck - some of the three matching criteria didn't work. If you have examples of these self-organised submissions, please post links to them so that I can verify.

**Comment by Talishask** [comment]
@pbanaszkiewicz Thank You! This definitely helped to clear this issue up for me. 
No fix is needed.
