### ISSUE TITLE
Move "Circuits" Tag up on the list

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/amy#1574]
I would like to move the "Circuits" tag up higher on the list. To get to the button you have to scroll down in that box 

I propose moving it between "LC" and "Wise"

**Comment by maneesha** [comment]
Thanks for bringing this up @sheraaronhurt !
While we are looking at this, what overall order would you recommend for all the items in the "tags" menu?

**Comment by pbanaszkiewicz** [comment]
Suggested by @fmichonneau: add a numerical field to `Tag` model that will keep tag's sorting priority (lower value first - 1, 2, 3, 4...). This way it's possible to edit tags in Django Admin and change their order.

**Comment by sheraaronhurt** [comment]
@maneesha 
Sorry for the delay: 

- DC
- LC
- SWC
- Circuit
-Pilot
-TTT
-online
-ITT (is this Instructor Train the Trainer?)
-cancelled
-unresponsive
-stalled (can we change to postponed?)

**Comment by pbanaszkiewicz** [comment]
@sheraaronhurt I updated the order before releasing new AMY version. Since you omitted some existing tags, I added them at the end. New order:

1. 'DC',
2. 'LC',
3. 'SWC',
4. 'Circuits',
5. 'Pilot',
6. 'TTT',
7. 'online',
8. 'ITT',
9. 'cancelled',
10. 'unresponsive',
11. 'stalled',
12. 'LMO',
13. 'LSO',
14. 'WiSE',
15. 'hackathon',

You'll be able to edit this order anyway.
