### ISSUE TITLE
Workshops with tag "circuits" don't trigger the 7 days post-workshop email

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1681]
example: https://amy.carpentries.org/workshops/event/2020-07-21-nmcsa-online/
cc: @Talishask

**Comment by pbanaszkiewicz** [comment]
The reason why Circuits events are omitted is that "LC" /  "DC" / "SWC" is expected. I can extend the list to cover Circuits as well, however please confirm what should show in the email subject (the template is `Completed {DC, SWC, LC} workshop at {site} on {dates}`).

**Comment by Talishask** [comment]
@sheraaronhurt - Piotr is working on an update so that the post workshop email also goes out for Circuits/Mix-n-Match workshops. For the Circuits workshops specifically - would you like the subject of the message to :
- include the word circuits like: Completed **Circuits** workshop at {site} on {dates}).
or
- show DC/LC/SWC but nothing if the workshop is circuits like: Completed workshop at {site} on {dates}).

**Comment by sheraaronhurt** [comment]
Thanks @Talishask and @pbanaszkiewicz 

I would prefer the 2nd option: show DC/LC/SWC but nothing if the workshop is circuits like: Completed workshop at {site} on {dates}).

Could it say Completed "Carpentries" workshop? If that require more work then, I would say to keep it as is.

**Comment by pbanaszkiewicz** [comment]
@Talishask @sheraaronhurt currently the subject for 7days-post-workshop email template shows:
```
Completed {% if workshop_main_type %}{{ workshop_main_type }}{% endif %} workshop at {{ workshop.venue }} on {{ dates }}
```

The part `{% if workshop_main_type %}{{ workshop_main_type }}{% endif %}` conditionally displays DC/LC/SWC. In case of Circuits this part will not display anything. @fmichonneau can add `{% else %}"Carpentries"` in the middle to support `Completed "Carpentries" workshop` scenario.
