### ISSUE TITLE
Require confirmation that workshops <2 mos away may not be possible.

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#1683]
Right now if a person filling out a *request* or *inquiry* form puts in a date that is less than two months away, they get a warning that says we can't guarantee things.  However, this warning often seems to be ignored.  

Based on conversations with @sheraaronhurt  and the Workshop Admin Team, we'd like to confirm this by adding one more checkbox to the mandatory boxes at the bottom of the *request* and *inquiry* forms that states:

* I understand that if my workshop is less than two months away, The Carpentries can not guarantee availability of Instructors and I may not be able to hold my workshop as scheduled.

Ideally this checkbox should only appear if the workshop is less than two months away.  As a fix for now, this can appear unconditionally on the *request* and *inquiry* forms.  This does not need to appear on the self organized form.

**Comment by pbanaszkiewicz** [comment]
@maneesha @sheraaronhurt as phase 1 I'm implementing this field as required and always visible.

As phase 2 I can make adjustments:
1. only require this field if the event is soon (2 months) - right now it's always required
2. hide and show the field along with the warning.

When the field is hidden, I have to enable conditional requirement, that's why the steps 1-2 are for the phase 2.

Please make a corresponding ticket for phase 2.
