### ISSUE TITLE
Consents: display new consents in profile editing history

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/amy#1993]
The editing history of a person's profile (the `/workshops/version/` endpoint, accessed by clicking on `Last modified` on the top of the profile) doesn't seem to display the values of the new consents system, only the old one.

**Comment by pbanaszkiewicz** [comment]
@elichad This is another ticket you can work on. I don't think there's an easy solution to displaying changes made to the new style consents, since they are following a relationship to a person, so I would suggest that you start with investigation first. I also think the other ticket #2302 is more important.
