### ISSUE TITLE
Warning (not error) when inhouse instructor training seats are exceeded

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2000]
Right now if you try to add in more seats than allowed, you get an error blocking you from continuing.  This should be a warning that notifies you but allows you to continue.

**Comment by maneesha** [comment]
This should apply to inhouse and public seats.  I'm also changing the tag to essential as it is currently blocking accurate data entry.

**Comment by pbanaszkiewicz** [comment]
@maneesha I'm unable to find this in the code. Where exactly does this occur? (Please provide steps to reproduce and optionally screenshots).

**Comment by maneesha** [comment]
@Talishask  can you share an example of where this happens? If you want to include screenshots, please email them to me & @pbanaszkiewicz  so as not to post private info here.

**Comment by Talishask** [comment]
@pbanaszkiewicz - 

It has primarily happened when I am correcting data or entering training seats manually.
- Take https://amy.carpentries.org/workshops/event/2021-06-15-ttt-online-SSI/ for example. When trying to edit or update one of the learner tasks to make the seat type "In-house', I receive the warning "This membership doesn't have any remaining in-house seats." and it does not allow me to change the seat type.
- Another example would be updating the membership in the task because I selected the wrong membership originally and getting a similar warning and blockage.

So, I think the steps to reproduce this issue are:
- Go to a training event
- select the edit icon for one of the learner tasks 
- select in-house or public seats when there are not enough in the membership
- select submit and you should see the error message

I have not seen this error on the https://amy.carpentries.org/requests/training_requests/. Instead, I have noticed a different issue with entering data on the training requests page. For example, I just went to the training requests page to add a test profile to this [training event](https://amy.carpentries.org/workshops/event/2021-06-15-ttt-online-SSI/) as an in-house seat type. The seat successfully added and I did not receive any errors or warnings. However, when you look at the event you will see that it changed the seat to public; likely because there are no in-house seats in the membership that was selected. This behaviour is also very troubling because we want to be able to track when people use more seats than are allowed.

Let me know if I can provide anymore information.

**Comment by pbanaszkiewicz** [comment]
@Talishask I was able to figure out and fix the errors. Thank you for your help!

**Comment by Talishask** [comment]
Awesome thanks
