### ISSUE TITLE
To do following recent AMY release

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2241]
I'm keeping a list here of things to come back to. No action needed until I update this issue.

To do

- [x] Any `<XX> Homework` training progress should be changed to `Lesson Contribution`. Original date and URL should remain the same.
- [x] Any `<XX> Demo` training progress should be changed to `Demo`. Original date should remain the same.

**Comment by maneesha** [comment]
@pbanaszkiewicz I think this is complete - can you verify?

**Comment by pbanaszkiewicz** [comment]
@maneesha 

Re 1: I'm seeing 3871 training progress entries with `<XX> Homework` instead of `Lesson Contribution`.
Re 2: I'm seeing 3838 training progress entries with `<XX> Demo` instead of `Demo`.

Should we leave them be in the database, or migrate them? Maybe they are benign, I think I developed the logic in a way that accounts for Carpentry-specific homework or Demo.

**Comment by maneesha** [comment]
We should run a migration on this data.

**Comment by pbanaszkiewicz** [comment]
Fixed by SQL update.
