### ISSUE TITLE
Update links to documentation

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2290]
Clicking on "Users Guide" in the top right menu should take you to https://carpentries.github.io/amy/users_guide/admin_index/ (not https://carpentries.github.io/amy/users_guide/)

Additionally the users guide should open with the index page and no menus expanded (currently the Projects menu is expanded when you to to https://carpentries.github.io/amy/)

**Comment by pbanaszkiewicz** [comment]
@maneesha I don't think I can control "Projects" menu being open or not, unfortunately. I can remove subitems (Projects, Automated emails, Memberships and so on), but it means they will be not accessible from the menu.

**Comment by maneesha** [comment]
We want to have those menu options so I don't want to remove those.  
I'm trying to figure out why the default view has "Projects" open.

**Comment by maneesha** [comment]
Additionally -the "Users Guide" link referred to above applies to the admin view.  I have updated the link in the first comment in this issue accordingly.  

In the instructor dashboard view (https://amy.carpentries.org/dashboard/instructor/)  the menu option is "Help" and currently goes to a different link.  this should go to https://carpentries.github.io/amy/users_guide/community_index/.

**Comment by pbanaszkiewicz** [comment]
@maneesha:
> Additionally the users guide should open with the index page and no menus expanded (currently the Projects menu is expanded when you to to https://carpentries.github.io/amy/)

I spent some time on this one and figured it's an upstream-upstream issue.

1. We depend on mkdocs' fork of readthedocs theme
2. readthedocs theme uses JS to find current page in the navigation.

I think the issue is in the JS code somewhere here:
https://github.com/readthedocs/sphinx_rtd_theme/blob/master/src/theme.js#L130

I think for some reason this code finds "Projects" navigation item:
![obraz](https://user-images.githubusercontent.com/72821/204091501-2273025e-f96c-4b6f-ba44-8157217e5040.png)
and sets it as "current" to indicate navigation item user has entered. In the sample above it should be "Server infrastructure" instead.

I can attempt to write custom code to fix this issue, or submit upstream bug. In any case I would split current ticket and move the collapse issue to it's own ticket.
