### ISSUE TITLE
Recording trainee participation at TTT event 

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2342]
For Instructor Training, we record trainee participation twice.

First, we record them by giving them a role of `learner` at the event they attended, matching them to a membership if applicable.

Then we record that they completed the `training` step towards trainee progress.  Here, we are able to note whether they passed, failed, or were asked to repeat.  We then add in the associated training event.  In this step, we would like to see this automatically fill in the TTT event they were a learner at.  If they were a learner at more than one TTT event, then we should see a drop down that is limited to just the events they were a learner at, rather than seeing all events as options.

EDIT to add additionally -- As expected, a trainee may have multiple `training` steps completed.  However, we should not allow multiple `training` steps for the same event.

**Comment by elichad** [comment]
Due to the way our forms only get the available options when you click into the `<select>` element, we can't easily auto-fill* this data. We can, however, filter the options to only show events for which the trainee has a learner task, which should make this form much easier to fill.

*In some places, like the award form, we _can_ auto-fill based on the initial state of the form. However, the event can't be filled in on the training progress form unless the "Training" requirement is selected, which is never part of the initial state.
