### ISSUE TITLE
Add "consent to publish profile" to instructor training application

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2367]
Based off the conversation in #2162, we should have a consent in the instructor training application that reads:

"The Carpentries will not make public any of your personal data when going
through the application process. However, once certified, do you consent to
your name and any linked social media accounts being published on The
Carpentries website?"

This should be migrated to the publish profile consent once the person profile is created from the application.

**Comment by pbanaszkiewicz** [comment]
This needs to be a separate term from the one used when user logs in for the first time.

**Comment by elichad** [comment]
I can imagine us making a similar change for the `may-contact` consent, along the lines of "The Carpentries will contact you about the progress of your application. Once certified, can we also contact you for volunteering opportunities, surveys, feedback, etc.?"

Since these still map to the same consent terms, just with different text, I think it would be better to add an optional `training_content` field for existing terms rather than create new terms. The training request form could then display the `training_content` (and fall back on the existing `content` if `training_content` is unset).
This also lets us keep using the same 'required consent for a profile' flag to select what terms to display on the form.
