### ISSUE TITLE
Use member registration code on all workshop request forms

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2380]
~This may need to be broken out into several issues.~  *DONE*

On the workshop request forms, we would like to add the following question:

> Are you affiliated with a Carpentries member organisation?

- If no, proceed as normal.
- If yes, the user should be asked for a registration code.  This should be verified to be a code associated with a current membership.  
- If it is not a currently valid code,  give the user a warning (example text below). Allow them to proceed. Include the warning text in the confirmation email that the user receives.
- Add a filter to the workshop request view to filter for requests with invalid codes. (See new issue #2398)
- When that workshop request form is accepted and turned into an event, the membership associated with that code should automatically fill in the "membership" field. (See new issue #2399)

**Comment by maneesha** [comment]
Suggested warning text:

> It seems you have entered an invalid member code.  Please make sure you have the current year's code and do not have any typos.  If the code looks correct, please proceed to submit your form. A member of our team will follow up with you if there are any problems that require your attention.

**Comment by maneesha** [comment]
For workshop requests, the code should be valid as of 60 days **before** the membership start date, and end as of the actual membership end date.

**Comment by elichad** [comment]
Discussed in depth with WAT on 18 October. Summary below.

1. We can remove the "are you affiliated with a member org" question - as the member code isn't a required field, we can just have that by itself. That said, we could dynamically show/hide some questions based on the affiliation question. I'd rather avoid this if we can because dynamic things add more room for error.
2. would be convenient to auto-fill the institution after a code is entered, but this is tricky to navigate when members may share /donate workshops with other institutions
3. if a user enters an institution which has a membership, but doesn't enter the member code, create a way of flagging this to admins. This might happen where someone isn't in contact with membership contacts at their institution, or just has forgotten their code.
4. agreed that code validation should be hard, not soft - users should know who to speak to to check their code; we should make sure our error messaging is clear enough for member contacts to troubleshoot.
5. member code question should not be asked on SOW form or inquiry form, as we don't use that info and there's more scope for confusion (users submitting these forms may be completely unaware of the membership program)
6. extra task: Send email to member contact when a workshop request is submitted using their code. This reduces the chance of someone taking a donated/shared code and requesting more workshops than they were meant to without the knowledge of the lead contact.
