### ISSUE TITLE
Assign learner TTT task membership based on code in training application

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2397]
This can happen after #2379.
When we assign a learner task at a TTT event, we can assign it to a membership.  This should automatically fill in the membership associated with the code in that learner's TTT application.  We should still have the option to remove that associated membership.

**Comment by elichad** [comment]
From discussion with ITT: ideally there should also be a way to assign memberships to tasks automatically during bulk matching (i.e. select trainees with different codes, match them to a training, and AMY takes care of matching the membership up).

This expands the scope of this task a bit, but it should be possible (especially since we added a bulk error handling pattern in #2471)

**Comment by elichad** [comment]
Update to the bulk matching thoughts - this would actually go best with a feature like #2562. Currently, it wouldn't bring much benefit, as you still need to search for individual attendees to match them to a training anyway.
