### ISSUE TITLE
Actions when trainee submits "Get involved" 

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2472]
After a trainee successfully submits a "Get involved" step, the trainee can not currently view, edit, or delete their submission, and the trainee is able to create another submission.

The trainee should see the following: 

* The trainee should see a summary of their submission with a message that says "Thank you. Your submission will be reviewed in 7-10 days."   
* The trainee should be able to edit or delete their submission.  
* The trainee should not be able to submit another entry.

**Comment by elichad** [comment]
To allow trainees to update/delete their submission, the easiest (and probably most robust) way is to split the form on to a separate page. I think this might work better for the original submission too, especially in the case where they have been asked to repeat the step, as that can end up with quite a lot of text. Here are some screenshots of what that looks like. @karenword @klbarnes20 what are your thoughts on this?

Note I'm aware of some display improvements that could be made (e.g. contrast of the yellow text and visual distinction of the submission details vs info text), I'm asking just about the workflow here.

Before making a submission:
![Get Involved not submitted yet. Button "Submit a Get Involved activity"](https://github.com/carpentries/amy/assets/20683271/43969890-9a7a-4e6f-bbf8-9298ece7a0ea)
Alternatively, when asked to repeat:
![Get Involved asked to repeat as of 20 July 2023. Administrator comments: URL does not go to a workshop website. Details of your submission are below. (Submission details omitted.) Button "Submit another Get Involved activity"](https://github.com/carpentries/amy/assets/20683271/3a724e37-7f5e-4470-bb14-281a381ae429)
Clicking the button above takes you to the create submission page (edit page is much the same with title "Update your Get Involved submission"):
![New page titled "Submit your Get Involved activity" with the Get Involved form, which has not been otherwise changed](https://github.com/carpentries/amy/assets/20683271/b6476b4f-2d56-4d0c-819a-bef25586040f)
After submitting:
![Get Involved not evaluated yet as of 20 July 2023. Your submission will be evaluated within 7-10 days. You may update or delete your submission before it is evaluated. If you delete it, you will be allowed to create a new submission afterward. (Submission details omitted.) Buttons "Edit" and "Delete"](https://github.com/carpentries/amy/assets/20683271/c77e8cac-8b60-4ce8-a705-f0afc77a0041)

**Comment by karenword** [comment]
LGTM! Thanks @elichad !

**Comment by klbarnes20** [comment]
I really like this @elichad!
