### ISSUE TITLE
Update language about state of each checkout progress step

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2476]
We should use more meaningful language (passed, pending, completed, etc.) about each step towards instructor training certification.

- Training: Options are incomplete, passed, failed, asked to repeat
- Demo: Options are incomplete, passed, failed, asked to repeat
- Welcome Session: Options are incomplete, complete.  Testers reported the term "passed" as confusing, as the only thing to do is show up.  Participation is not evaluated as it is for training, demo, and get involved. _(Note: do we want to allow “failed” here? The only thing I can think of is if the welcome host reports a CoC violation during the welcome session)_
- Get involved:  Options are incomplete, passed, asked to re-submit _(same thing - do we want to allow “failed” here?)_

**Comment by maneesha** [comment]
@karenword  @klbarnes20  do the terms above sound good to you?

**Comment by klbarnes20** [comment]
I thought we were trying to not use the word "failed" particularly with demos and especially if the AMY user can see it.

**Comment by maneesha** [comment]
I believe for almost all trainees, they will not fail, but rather be asked to repeat.
"Failed" was a special case for no-show with no contact at a training, or egregious problems in their presentation and interaction (like CoC violation).  Is that right?

**Comment by karenword** [comment]
I think there is a broader question about how things like CoC violations are handled in our database. The CoCc should really be the ones making a determination about how to handle a violation, and I don't think a user-viewable "failed" status is appropriate while they deliberate. Following a decision, someone will most likely either be excluded from the community (at which point any record of that should be general, not specific to a task) or conditionally accepted, in which case we would ask to repeat.

**Comment by maneesha** [comment]
Ok, that makes sense.  @karenword would you then like to remove "failed" from all the items above? Can everything else remain as is?

**Comment by karenword** [comment]
Yes I think the only thing that needs a failed, currently, is Training.

**Comment by elichad** [comment]
I would prefer to keep this UI as closely aligned as possible to how we handle things on the admin side (both for transparency and for ease of coding/maintenance). If we already avoid using the Failed state except when it's really needed, why hide it?

In the case of a "failed pending CoCc investigation" type status, I'd suggest using the "Not evaluated yet" state on the progress, rather than using the Failed state and hacking it out of the UI.

If we definitely don't want to use the word 'failed,' but the state of the training progress is Failed, and any CoCc investigations etc are completed, what should be presented in the trainee view? 'Not completed yet' and 'not evaluated yet' don't seem sufficient in that case.

**Comment by elichad** [comment]
Separate question: should the admin notes also be visible in the case where the state is Failed or Asked to repeat? 

This is mentioned for the Get Involved step specifically in #2473 but I want to check about this more widely.
