### ISSUE TITLE
Your Training Progress Top Text Validation

### ISSUE THREAD

**Issue by Talishask** [carpentries/amy#2508]
The text at the top of the 'Your training progress' page does not seem to be validating correctly. I have tried a few different combinations of progress status to see which messages would show up.

In this case, the message should not show up because training is failed:
![image](https://github.com/carpentries/amy/assets/45104071/e723f491-dc94-4ceb-889b-e3cc99b058f1)

If I remove the welcome session progress the message returns to the appropriate language:
![image](https://github.com/carpentries/amy/assets/45104071/72f09a2a-f514-4c16-83ec-26d7d0afc475)

Another case where this is showing incorrectly when the training is asked to repeat:
![image](https://github.com/carpentries/amy/assets/45104071/0ac8f478-f8b4-4112-bf28-608462084903)

If I remove the demo progress the message returns to the appropriate language:
![image](https://github.com/carpentries/amy/assets/45104071/0017b201-b88a-44e9-bf0a-57b473b2f1d1)

**Comment by Talishask** [comment]
It looks like there are 4 messages:
1. "If you have recently completed a training or step towards checkout, please allow 7-10 days for this information to show up in your profile."
2. Checkout Deadline & Instructions
3. "Congratulations. You have successfully completed all steps towards Instructor certification. You will receive your certificate and more information by email in 1-2 weeks."
4. Congratulations, you're a certified Instructor!


Ideally, the validation would show each messages as outlined below:
1. (Message 1) If training progress is non-existent, asked to repeat, not evaluated, or failed.
  - The status of the other 3 steps should not have an impact here because there is no deadline if the person has not completed training.
2. (Message 2) This message should show when training status is passed, but not all the other steps.
3. (Message 3) The congratulations message should show when all items have been marked as passed, but the badge has not been awarded.
4. (Message 4) This message looks good. It should show up when an Instructor Badge is awarded, regardless of any other steps.
  - Note I did not include any validation on the steps because historically there are a lot of differences in how things were recorded.

**Comment by elichad** [comment]
Thanks for your thorough testing @Talishask ! I'm documenting my thoughts here for clarity.

The current case with the messages is as follows:
* Message 1 is shown when no progress is present for any step.
* Message 2 is shown when any step is _passed_, and includes the checkout deadline if progress for the training step _exists_. It includes the line "Please review your progress towards Instructor certification below." and the link to the checkout page, which distinguishes it from Message 1 if training has not been completed, but other steps have been passed.
* Messages 3 and 4 work as you stated.

I'm going to update this so that Message 2 is shown when progress for any step _exists_, and includes the checkout deadline only if training has been _passed_. This means that for every screenshot you included, the message will read:
>Please review your progress towards Instructor certification below.
If you have recently completed a training or step towards checkout, please allow 7-10 days for this information to show up in your profile.
Visit our [checkout page](https://carpentries.github.io/instructor-training/checkout) for more information.
