### ISSUE TITLE
Update intro text for Instructor Training application

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2591]
The instructor training application currently has this text at the top:

> For trainees selected by Carpentries member organizations or groups that have arranged for training, it serves as a trainee Profile Creation form. This creates an entry in our database and allows us to record attendance and track your progress through the Instructor certification process. Form responses are not reviewed in detail but may be used in programmatic assessment. Please note that this form is separate from event registration. Your site contact will provide you with instructions to register for an Instructor Training event. In response to the first question, please select Profile Creation for Pre-approved Trainees and enter in your provided registration code.

Consider changing the final sentence of that paragraph to note that they need to enter their code and their Eventbrite registration info.

Tagging @karenword  for feedback.

**Comment by karenword** [comment]
Thanks @maneesha  -- this one is more complicated because there are diverse time points at which a trainee may be instructed to complete this form. In the unusual case where a member directs them to the form before they register for training, it is ok for them to complete the form as long as they have a membership code. The eventbrite link will not be enforced. So, I think this text is ok as-is.

**Comment by maneesha** [comment]
OK, I will close this issue.
