### ISSUE TITLE
Scheduled/completed emails should be visible from the related object

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2622]
For example, this [membership onboarding email](https://test-amy2.carpentries.org/emails/scheduled_email/aa440d84-dff4-49ac-8f33-a9419891a254/) should be visible from [this related membership object](https://test-amy2.carpentries.org/fiscal/membership/47/).

We would want to do this when the related object is a membership or an event. We may not want to do this when the related object is a person.

**Comment by pbanaszkiewicz** [comment]
@maneesha As far as I know, non-admin users don't have access to administrative pages for persons. Please correct me if I'm wrong.

**Comment by pbanaszkiewicz** [comment]
@maneesha I added the display of related scheduled emails to following models:
* Event
* Person
* Membership

There are models used as related to the scheduled emails, but we have no place to display the list of scheduled emails:
* Award
* Instructor Recruitment Signup

@maneesha let me know if you want to add that list of related scheduled emails to any of those 2 remaining models, you can also tell me where you want that list displayed.

**Comment by maneesha** [comment]
I think my language above came out confusing. 
A non-admin user can not view any pages other than their own Person profile. Emails should not show in their own Person view.

Emails should show in all admin views.

**Comment by maneesha** [comment]
For the remaining two models:

* Instructor Recruitment Signup - display on recruitment page (example: 
https://test-amy2.carpentries.org/recruitment/process/100/).  Another below under the existing table.

* Award - display in Person view

**Comment by pbanaszkiewicz** [comment]
> Would it be difficult to have all emails sent to a Person display on that Person's admin view?

Currently yes, but we could make it an enhancement for v4.4.

**Comment by pbanaszkiewicz** [comment]
@maneesha 
For the instructor recruitment signups this is going to be the view; I used the table since email is per signup, not per whole recruitment.

<img width="1784" alt="image" src="https://github.com/carpentries/amy/assets/72821/60cb9390-eb76-4bf0-b9ac-0c98db159211">

<img width="1789" alt="image" src="https://github.com/carpentries/amy/assets/72821/bdd0cfa6-5ba2-4018-96c0-e8b56ca1d03c">


It does make the table cramped, so if you prefer another way of displaying it, eg. separate table underneath that table, let me know.

**Comment by pbanaszkiewicz** [comment]
@maneesha Similarly for awards I had to create a separate list there:
<img width="1788" alt="image" src="https://github.com/carpentries/amy/assets/72821/20157ab3-f988-46c3-b3c1-07478746f713">

**Comment by maneesha** [comment]
All looks good!
For the Instructor signups - this would end up being a bulleted list, where we would see an additional email when the Instructor is confirmed/denied, right? Also would there ever be a case where there was no related email?

**Comment by pbanaszkiewicz** [comment]
@maneesha 
> For the Instructor signups - this would end up being a bulleted list, where we would see an additional email when the Instructor is confirmed/denied, right?

Yes. Here's an example - instructor Kelly Hall was first confirmed, then declined and we can see both emails:
<img width="1475" alt="image" src="https://github.com/carpentries/amy/assets/72821/a92835a2-ccd3-4537-aed6-c70fa41ca32a">


> Also would there ever be a case where there was no related email?
I don't think so. It's possible with my fake data, but in reality we have covered these actions:
1. admin signs instructor up for a workshop (on their behalf)
2. instructor signs up for a workshop (themself)
3. instructor is confirmed to teach at a workshop
4. instructor is declined from teaching at a workshop

If you're asking "would there be a scheduled email without related object" this is not possible currently. All scheduled emails will have a related object, however it's always 1 object.
This could be improved in future so that we can easily track e.g. all emails a specific user was involved with or all emails concerning one event. I think I suggested to you that this could be non-MVP improvement for v4.4.
