### ISSUE TITLE
Flag if organizer has access to Eventbrite

### ISSUE THREAD

**Issue by amyrbrown** [carpentries/amy#406]
Eventbrite allows us to give people adminstrator permission for their event page. However, the Eventbrite UX for figuring out who has access to which event is _awful_. It would be nice if we could somehow keep track of who has access to an event's Eventbrite page in AMY.

**Comment by pbanaszkiewicz** [comment]
Check if this is what we want: https://www.eventbrite.com/developer/v3/formats/organizer/

**Comment by maneesha** [comment]
I don't think this is what Amy was referring to.  I don't see this in the Eventbrite API, but if you go into the standard Eventbrite interface, you can assign events to users (not users to events).  Go to Account Settings --> Multiuser access and you can assign events to users.  You can also see what users have what events assigned to them.

From what I've seen there's no way to see what events have what users assigned to them -- I think that's what this issue was about and is something I'd find really useful.

You can also see that there are a TON of users listed - many of those have not participated in a workshop in at least a year.  I'd like to remove those as well but I don't see a way of seeing who's who unless I open each user's profile.

**Comment by gvwilson** [comment]
@maneesha is this something you want?

**Comment by maneesha** [comment]
Closing - stale.
