### ISSUE TITLE
Add a notification system

### ISSUE THREAD

**Issue by pbanaszkiewicz** [carpentries/amy#795]
Something similar to what GitHub has.

We have a number of features (workshop website updated, invoice status changed, etc.) that could use a notification system for admins.

**Comment by gvwilson** [comment]
See also #524.

**Comment by pbanaszkiewicz** [comment]
@gvwilson I was thinking about GitHub-style notifications. https://github.com/django-notifications/django-notifications this looks very promising.

**Comment by gvwilson** [comment]
See also #516

**Comment by gvwilson** [comment]
See also #803

**Comment by gvwilson** [comment]
See also #763

**Comment by pbanaszkiewicz** [comment]
https://djangopackages.org/grids/g/notification/

**Comment by maneesha** [comment]
Currently each of the Regional Coordinators gets an email when a workshop request form comes in for their region.  I think the same thing should happen once we get the three-way form (inquiry, request, self org) in place. 

@sheraaronhurt  @Talishask  What other kinds of notifications would you want to see?  Would you want external notifications (like emails)?  Notifications when you log in to AMY?  Some other method of notification?

We have this scale in place to prioritize things.  Since this isn't a well defined fix yet, I'd suggest option 3.  Let me know what you think.

**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by Talishask** [comment]
3 - I am happy with the helpscout notifications, but I do think it would be useful to have some popup notification in AMY when there are still unassigned pending workshop requests in your region. This would help to ensure that workshop requests aren't overlooked, but also not be too overwhelming with notifications.

**Comment by sheraaronhurt** [comment]
3 - and agree with @Talishask  like the idea of notification for pending requests.

**Comment by maneesha** [comment]
Closing this as we now have other systems to notify workshop admins of pending requests, changes to website, etc.
